site_name: Maycon Ferreira Silva - CV
site_description: First and Second Level Support | Cloud & Infrastructure
site_author: Maycon Ferreira Silva
site_url: https://mayconsilva7.github.io/
use_directory_urls: true

theme:
  name: material
  language: de
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - content.tabs.link
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

  font:
    text: Source Sans 3
    code: JetBrains Mono

  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/MayconSilva7/MayconSilva7.github.io
repo_name: MayconSilva7.github.io

nav:
  - Home: index.md
  - Lebenslauf: Maycon_Silva_CV.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - def_list
  - abbr
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - tags
  - rendercv:
      cv_datasource: maycon_de.yaml

extra:
  base_url: /
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MayconSilva7
      name: GitHub Profile
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/maycon-ferreira/
      name: LinkedIn Profile
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/maycon.ferreirasilva.9/
      name: Facebook Profile
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/maycon_ferreir/
      name: Instagram Profile
    - icon: fontawesome/solid/envelope
      link: mailto:mayconferreirasilva7@gmail.com
      name: Email

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2026 Maycon Ferreira Silva
